SELECT NAME, COUNT(NAME) AS COUNT FROM ANIMAL_INS WHERE NAME != 'NULL' GROUP BY NAME HAVING COUNT(NAME)>1 ORDER BY NAME

WITH TEMP_TABLE as (SELECT NAME, count(NAME) as COUNT FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
ORDER BY NAME)
SELECT * FROM TEMP_TABLE
WHERE COUNT > 1