-- 코드를 입력하세요
WITH TEMP_TABLE as (SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT FROM ANIMAL_OUTS GROUP BY HOUR(DATETIME) ORDER BY HOUR(DATETIME) ASC)
SELECT * FROM TEMP_TABLE WHERE HOUR>=9 AND HOUR<20